Naam = input("Wat is uw naam? ")
Adres = input("Wat is uw adres? ")
Postcode = input("Wat is uw postcode? ")
Woonplaats = input("Wat is uw woonplaats ")
print("------------------------------------------")
print("|    Naam         : " ,Naam,)
print("|    Adres        : " ,Adres,)
print("|    Postcode     : " ,Postcode,)
print("|    Woonplaats   : " ,Woonplaats,)
print("------------------------------------------")