maanden = ("maandag","dinsdag","woensdag","donderdag","vrijdag","zaterdag","zondag")
print("Alle dagen van de week:")
print(maanden[0], maanden[1], maanden[2], maanden[3], maanden[4], maanden[5], maanden[6])
print("De werkdagen zijn:")
print(maanden[0], maanden[1], maanden[2], maanden[3], maanden[4])
print("De weekenddagen zijn:")
print(maanden[5], maanden[6])
print("Alle dagen van de week in omgekeerde volgorde zijn:")
print(maanden[6], maanden[5], maanden[4], maanden[3], maanden[2], maanden[1], maanden[0])
print("De werkdagen in omgekeerde volgorde zijn:")
print(maanden[4], maanden[3], maanden[2], maanden[1], maanden[0])
print("De weekenddagen in omgekeerde volgorde zijn:")
print(maanden[6],maanden[5])